### ISSUE TITLE
Command failed: iwgetid --raw

### ISSUE THREAD

**Issue by s0nskar** [kevva/wifi-password#12]
```bash
$ wifi-password
>>> Command failed: iwgetid --raw
```
Platform: Ubuntu 16.04

**Comment by ndaidong** [comment]
I got the same issue.

![alt](http://i.imgur.com/C7WKDba.png)

Linux Mint 18 (Ubuntu 16.04 based)
Node.js v6.5.0

**Comment by s0nskar** [comment]
I don't think this repo is maintained anymore.

**Comment by kevva** [comment]
@s0nskar, yes, it is. If anyone knows of another way to get the SSID name I'd be happy to fix this issue.

**Comment by kevva** [comment]
Going to close this in favour of #9.
