### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by matiassingers** [kevva/wifi-password#3]
See [RReverser/WiFi-Password](https://github.com/RReverser/WiFi-Password)

**Comment by kevva** [comment]
@matiassingers, any idea if it's possible to convert this to a regular `.bat` file or likewise?

**Comment by matiassingers** [comment]
@kevva sorry no clue, quite a number of years since I last used Windows :stuck_out_tongue_closed_eyes:

**Comment by sindresorhus** [comment]
@kevva It's pretty clear how it works though. You can just implement the same parsing in Node.

`execFile` => `netsh wlan show profiles` and `netsh wlan show interfaces`.
