### ISSUE TITLE
Not able retrivew password.

### ISSUE THREAD

**Issue by hemanth** [kevva/wifi-password#8]
```sh
○ → wifi-password 
Your network doesn't have a password
```
On `14.0.0 Darwin Kernel Version` am I missing something?

Connected to a n/w with WPA2 secured password.

**Comment by kevva** [comment]
Can you run `security find-generic-password -D "AirPort network password" -ga ssid` and paste the output?

**Comment by hemanth** [comment]
```sh
○ → security find-generic-password -D "myNetworkPassword" -ga ssid
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

**Comment by kevva** [comment]
So the `-ga ssid` option doesn't work even after adding it to your keychain?

**Comment by hemanth** [comment]
Yup.

**Comment by kevva** [comment]
@sindresorhus, do you have any idea why this happens?

**Comment by sindresorhus** [comment]
I get the same. The reason this happens is because I have iCloud password syncing on, which means the wifi passwords are in the `iCloud` keychain, not the `System` one.

Your current check is also incorrect as it just get's the first password it finds, not the most recently used one.

**Comment by kevva** [comment]
@hemanth @sindresorhus could you test the new version?

**Comment by hemanth** [comment]
Works fine! Thanks. 

What was the fix?

**Comment by sindresorhus** [comment]
:+1: Works now :)
